FROM golang:1.19 AS build-stage
WORKDIR /app
COPY *.go ./
RUN go build helloWorld.go 
FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /app
COPY --from=build-stage /app .
CMD [ "/app/helloWorld" ]
# executa a app mas a imagem tem um tamanho final de 22.3MB
